# -*- coding: utf-8 -*-
"""Menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Pn__JHVQQ6yBaK4Dedb_O-lTKxj-IWq
"""

import streamlit as st

# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
    .css-1d391kg {
        color: #faf7f8;
    }
</style>
""", unsafe_allow_html=True)

st.title("Menú de enlaces")

# Diccionario con opciones y links
links = {
    "Bayes_Map": "https://bayesmap-kgxsvqhpmtdfukvp6qhfez.streamlit.app/",
    "Repositorio": "https://videos-class-ntxornvewsnmrkyvsuc7yu.streamlit.app/",
    "Probabilidad": "https://probabilidad-lc5nb3p6xetbsvadzjyk4y.streamlit.app/",
    "Rendimientos mensuales": "https://preciocierre-gwhq3lwwrabizqwtpynbje.streamlit.app/",
    "Galletita financiera": "https://galleta-bfmexnl9e76gglkaanadm3.streamlit.app/",
    "Hooke": "https://alterno-vtw6bhga4gudyeqba5suui.streamlit.app/",
    "BMV": "https://appbmv-f9igvhnh5sc7wjax66ukjs.streamlit.app/",
    "Shopping": "https://shopping-v3mvgyrmt8u9nyftebqnee.streamlit.app/",
    "Volatilidades": "https://colab.research.google.com/drive/1QzYhaLwjNyKB_8Vw13UvexFGZ1EbK8rl?usp=sharing",
    "Tipo de Cambio": "https://exchange-r68mzkn9bmgvfhket3fznp.streamlit.app/",
    "CAPEX": "https://colab.research.google.com/drive/1MxxbXHsQyF0FGYaG39HcvFrAfJNQCGqf?usp=sharing",
    "Buen humor": "https://colab.research.google.com/drive/1DYDu9I4B6_OLlBdUkAmzoilBp-sKl7O0?usp=sharing",
    "Resorte": "https://colab.research.google.com/drive/1_o-yUIe1TpOs53zwa0yaY8njrc8345lW?usp=sharing",
    "Calendario": "https://es.tradingeconomics.com/country-list/unemployment-rate",
    "Rendimientos": "https://colab.research.google.com/drive/1_CikKZh6PHS14xKAY0W3ymlLTduAe8fZ?usp=sharing",
    "SPP": "https://colab.research.google.com/drive/1Hs_f7QPnywU6Q2XGyxyNfUGx4QkHGmSJ?usp=sharing",
    "Calendario": "https://es.tradingeconomics.com/country-list/unemployment-rate",
    "Music": "https://5gaehenr8pbzfyadepdafg.streamlit.app/",
    "Alcohol": "https://alcohol-fqlvjbuf6rrr62dyeyqmjc.streamlit.app/",
    "Bayes": "https://colab.research.google.com/drive/1lOc_KbMZ3S3y1aA99zNPDe5qshNcjb9e?usp=sharing",
    "FED": "https://gmovmmbwsmkffrhsnurj8m.streamlit.app/",
    "Seguimiento Portafolio": "https://colab.research.google.com/drive/1PawFqbF9YJN5x3h1DZPGqXzDHcfwGIH6?usp=sharing",
    "Índice de Vivienda SHF": "https://b9cairxvwefxjbw9mnyepb.streamlit.app/",
    


}

# Menú desplegable
opcion = st.selectbox("Selecciona una opción:", list(links.keys()))

# Mostrar botón con enlace
st.markdown(f"[Ir a {opcion}]({links[opcion]})", unsafe_allow_html=True)
