# -*- coding: utf-8 -*-
"""Menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Pn__JHVQQ6yBaK4Dedb_O-lTKxj-IWq
"""

import streamlit as st

# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
    .css-1d391kg {
        color: #faf7f8;
    }
</style>
""", unsafe_allow_html=True)

st.title("Menú de enlaces")

# Diccionario con opciones y links
links = {
    "Buen humor": "https://colab.research.google.com/drive/1DYDu9I4B6_OLlBdUkAmzoilBp-sKl7O0?usp=sharing",
    "Bitcoin": "https://colab.research.google.com/drive/1S47s0rJq4uW4aFFeyevDd4GcI8r5qrDe?usp=sharing",
    "Music": "https://5gaehenr8pbzfyadepdafg.streamlit.app/"
    "Rendimientos": "https://colab.research.google.com/drive/1_CikKZh6PHS14xKAY0W3ymlLTduAe8fZ?usp=sharing"
}

# Menú desplegable
opcion = st.selectbox("Selecciona una opción:", list(links.keys()))

# Mostrar botón con enlace
st.markdown(f"[Ir a {opcion}]({links[opcion]})", unsafe_allow_html=True)